AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 120 # default: 80

# Scripts only have one class, do not need docs
Style/Documentation:
  Exclude:
    - "*.rb"

Metrics/ParameterLists:
  Max: 3
  CountKeywordArgs: false

# The default (10) is just to stringent for my taste
Metrics/MethodLength:
  Max: 15
