AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 120 # default: 80

# Scripts only have one class, do not need docs
Style/Documentation:
  Exclude:
    - "*.rb"
